[[order-reference]]
= Order reference

Used to provide a reference to the purchase order on which the Despatch Advice is based. 
There may be multiple Despatch Advices to cover one purchase order.
When all the lines of the Despatch Advice relate to the same purchase order, the order reference is indicated only in the header. 
When the lines of the Despatch Advice relate to different purchase orders, the order references must be indicated in the lines. 
The reference to Order Line-ID is required in the UBL syntax. To cater for scenarios where no order line reference exist a dummy value must be applied. The dummy value must consist of the characters **NA**.

.Example header level
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-30-2.xml[tags=ref-order]
----

.Example 1 of Line level
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-30-2.xml[tags=ref-orderline]
----

.Example 2 of Line level
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-30-2.xml[tags=ref-orderlinena]
----

It is also possible to refer to more than one order in one single despatch advice.
In this case there must not be an order reference on header level.
