= Version 3.0.1
[horizontal]
Release date:: 2019-05-15

[NOTE]
====
This release is a backward compatible minor upgrade, version 3.0.1 replacing the previous version 3.0.0 of OpenPEPPOL BIS document, other than the BIS Billing 3.0. The release includes changes to the BIS documents as well as the validation artifacts (VA's).
====

== Changes to BIS documents and validation artifacts
This release applies the following changes to the previosly published BIS 3.0 documents. This release does not include any changes to the BIS 2.0 documents. With the publication of this release the BIS 3.0 version become the mandatory version and the BIS 2.0 version become optional until the phase out date. For details see the migration plan <http://docs.peppol.eu/poacc/upgrade-3/migration/>.

* Message Level Response document lifecycle clarified	POACC-152
* Review comment removed in Invoice Response BIS 3	POACC-161
* Namespace added for catalogue response	POACC-163
* Parties image in Despatch Advice BIS added	POACC-183
* Floating point error when comparing decimals in some implementations. All use of the xpath function sum() adjusted/verified. (Both Billing and BIS Order/OrderAgreement)	POACC-184
* Message examples for Invoice response corrected.
* Documentation of syntax binding for Dispatch Advice corrected POACC-180
* Added a common structure validation rule for Norwegian organizational numbers and GLN numbers.
* Various minor text corrections and minor bug fixes.


== New BIS for Catalogue without Response
This release includes a new BIS document for a Catalogue without response. This new BIS contains the same Catalogue transaction (T19) as the Cataloge only BIS but without the Catalogue Response transaction (T58). This new BIS can be used for sending catalogues to buyers with requiring them to implment the capability for responding, and thus simplifying the implementation while sacrificing some of the functionality provided by the Catalogue Only BIS.

The version number of this new BIS is set as 3.0.1 to keep it aligned with other BIS documents.
