[[allowance]]
= Allowances and Charges

The order agreement transaction has Allowance/charge on header level.

The element `cac:AllowanceCharge` with sub element `cbc:ChargeIndicator` indicates whether the instance is a charge (true) or an allowance (false).

_Information on allowance and/or charges applies to the whole order agreement and is included in the calculation of the order agreement total amount._


* Several allowances and charges may be supplied
* Specification of TAX for allowances and charges, `cac:TaxCategory` with sub elements, shall be supplied
* The sum of all allowances and charges on the header level shall be specified in `cbc:AllowanceTotalAmount` and `cbc:ChargeTotalAmount` respectively. See <<totals>>


[allowance-calc]]
== Calculation of allowance/charge amount

Allowance and charge on document level consists of elements carrying information on the allowance/charge base amount
and the allowance/charge percentage. These are, if present in the invoice instance, used for calculating the allowance/charge amount.

If base amount is present, the percentage shall also be present, and if percentage is present, the base amount shall also be present,
and the calculation of the amount shall be:

====
stem:["Amount" =  "Base amount" times ("Percentage" div 100)]
====


.UBL example of Allowances and Charges on the document level, when TAX is VAT.
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-oa.xml[tags=allowance]
----
<1> ChargeIndicator = true to indicate a charge
<2> ChargeIndicator = false to indicate an allowance
<3> Base amount, to be used with the percentage to calculate the amount
<4> Charge percentage
<5> stem:["Amount" = "Base amount" times ("Percentage" div 100)]
