[[status-codes-1]]
= Status codes

.The following policies apply to the use of status codes:
* List of Status codes is fixed and can not be changed bilaterally.
* There are seven pre-agreed status codes (main statuses).
* Status code is sent from Buyer to Seller to inform the Seller about further processing of the invoice on Buyer side.
* Status code does not inform the business reason for the Status to the Seller (there is a clarification code for that).
* Every status can be the first status sent to the Seller but from there further statuses must follow a defined order (see <<invoice-response-process-rules>>, rule OP-BR111-R012).
* Maximum time for first response 3 days – The Seller should receive the first Invoice Response within 3 working days.
** By receiving the first Response message the Seller will know that an Invoice has been received by the Buyer and what its status is.
** However, if the Seller does not receive any response he should wait 3 working days before contacting the Buyer to query whether the Invoice was received.
** A Buyer who has received an invoice should therefore provide a first Response before that time to notify the Seller that it has been received and what its status is.
* The minimum set of Statuses that must be supported by a Buyer is “Message acknowledged”, “Rejected” and “Approved”.


.The columns in the below table shall be understood as follows:
[horizontal]
Status code:: The code that defines the status of the reference document, e.g. AP.

UNECE name:: The name of the code, based on UNECE code list 4343.

UNECE definition:: The definition of the code, based on UNECE code list 4343.

BIS usage:: An explanation of how the UNECE definition of the code shall be interpreted and applied in transactions that follow this BIS.

Response expected::
Indicates that the Buyer expects a response from the Seller in accordance to the information given in the Invoice Response.
If no response is expected, then the Buyer will proceed with the processing of the invoice without interruption.
If a response is expected, then the Buyer will not proceed with the processing until the Seller has provided the response (externally).

Clarification required:: Indicates that when Invoice Response message contains this code then a clarification must be provided by the Buyer in the form of a Status Reason code (See {link-codelist}) or text or both.

Mandatory::
Indicates that a Buyer who supports this BIS shall at minimum be able to report these statuses in the processing of the invoice.
In other words, the Seller can at minimum expect to receive this status information.

Final::
Indicates that this is a final status in the processing of the referenced invoice.
The Seller will not receive any further Invoice Response messages referencing this invoice.

.The Status codes used in an Invoice Response message are defined in the below table and are a subset UNECE code list 4343 with additional codes.
[cols="1h,1,3,3,1,1,1,1",options="header"]
|====
|Status Code
|UNECE name
|UNECE definition
|BIS usage
|Response expected
|Clarification Required
|Mandatory
|Final
|AB |Message acknowledgement |Indicates that an acknowledgement relating to receipt of message or transaction is required. |Status is used when Buyer has received a readable invoice message that can be understood and submitted for processing by the Buyer. |NO |NO |YES |NO
|IP |In Process |Indicates that the referenced message or transaction is being processed. |Status is used when the processing of the Invoice has started in Buyers system. |NO |NO |NO |NO
|UQ |Under query |Indicates that the processing of the referenced message has been halted pending response to a query. |Status is used when Buyer will not proceed to accept the Invoice without receiving additional information from the Seller. |YES |YES |NO |NO
|CA |Conditionally accepted |Indication that the referenced offer or transaction (e.g., cargo booking or quotation request) has been accepted under conditions indicated in this message. |Status is used when Buyer is accepting the Invoice under conditions stated in ‘Status Reason’ and proceed to pay accordingly unless disputed by Seller. |NOfootnote:[When an invoice is conditionally accepted (CA) the Buyer will proceed with the processing according to the conditions it has stated.
The Seller may still respond externally if he has comments or objections to the conditions given.] |YES |NO |NO
|RE |Rejected |Indication that the referenced offer or transaction (e.g., cargo booking or quotation request) is not accepted. |Status is used only when the Buyer will not process the referenced Invoice any further. +
Buyer is rejecting this invoice but not necessarily the commercial transaction.
Although it can be used also for rejection for commercial reasons (invoice not corresponding to delivery). |YES |YES |YES |YES
|AP |Accepted |Indication that the referenced offer or transaction (e.g., cargo booking or quotation request) has been accepted. |Status is used only when the Buyer has given a final approval of the invoice and the next step is payment |NO |NO |YES |YES
|PD with PPD (1) |Partially Paid |Indicates that the referenced document or transaction has been partially paid. |Status is used together with Clarification Reason code PPD, only when the Buyer has initiated the payment of the invoice without having paid the accepted amount in full. |NO |NO |NO |NO
|PD |Fully Paid |Indicates that the referenced document or transaction has been paid. |Status is used only when the Buyer has initiated the payment of the invoice. |NO |NO |NO |NO

|====

(1) Status code PD (Paid) together with Clarification Reason code PPD (Partially Paid) is the case when an invoice is partially paid with the intention of later paying the full invoice amount as was accepted.

The sequence of the status codes is fixed to allow the Seller, as receiver of the Invoice Response message, to advance the status of the invoice in his systems in an orderly way. See <<invoice-response-process-rules>>.
This requires the Buyer to be conservative in reporting status and only advance an invoice when the status is reasonably certain.

The status of an invoice must advance in the following sequence, but any status may be the first one used or may be omitted.

1.  AB – Message acknowledgement
2.  IP – In process
3.  UQ – Under query (may be repeated before moving forward)
4.  CA – Conditionally accepted
5.  RE – Rejected
6.  AP – Accepted
7.  PD – Paid, can be in steps, partially paid and then paid.

.Examples of status advancement:
====
1.  If an invoice is paid right after being received, the Buyer can report with a single Invoice Response using the code PD.
2.  If an invoice has been put under query then following the response from the Seller, the Buyer may advance it to any of the following codes:
[horizontal]
 CA:: conditionally accepted
 RE:: Rejected
 AP:: Accepted
 PD:: Paid
====

Deviations from this sequence must be handled manually between the trading parties.
As example, if a Buyer has stated that an invoice has been accepted they can not later send an Invoice Response indicating that it is under query or rejected.
This does however not prohibit the Buyer from changing his decision, but he must report that to the Seller by other means than by using an Invoice Response.

The fixed order simplifies the automation of the processing for the receiver of the Invoice Response.
