[[benefit]]
== Benefit

Based on success with automation of invoicing, there is a growing interest in automation of ordering also.
This approach has two dimensions: Support further automation of invoicing and using structured catalogues as basis for ordering.
Implementing this BIS is an important step for many companies and government agencies towards full procurement automation.

For the sellers, the approval, picking and invoicing can be automated significantly.

For the procuring agency, approval and accounting of invoices can be automated and ordering can be structured by use of catalogues.

Other potential benefits of using this BIS are, among others:

* Can be used by procuring agencies as step towards automation of procurement. The flexibility of the specifications allows the buyers to gradually automate and structure ordering, based on a cost/benefit approach.
* SME can offer their trading partners the option of exchanging standardized documents in a uniform way and thereby move all orders into electronic form.
* Large companies can implement this BIS as standardized documents for general operations and implement custom designed bi-lateral connections for large trading partners.
* Can be used as basis for restructuring of in-house processes of orders and invoices.
* Significant saving can be realized by the procuring agency by automating and streamlining in-house processing.
* Significant saving can be realized by the sellers by automating and streamlining in-house processing.
Linking to picking and invoicing can be improved significantly based on increased order quality, restructuring of invoice dispute resolution and shorter payment cycles.
* For the procuring agency, invoice automation and ordering can be structured.
