[[use-case-3-negative-response-violation-of-syntax-and-business-rules]]
= Use Case 3 – Negative response – violation of syntax and business rules

This use case is a message level response containing errors and warnings due to violation of syntax and business rules.

[cols="2s,6",options="header"]
|====
|Use Case number
|3

|Use Case Name
|Negative response – violation of business rules, business rules warnings and violation of syntax

|Use Case Description
|This use case is a message level response based on a business document containing errors and warnings due to violation of business rules and syntax.

|Parties involved
|BusinessDocumentSender, MLRReceiver +
BusinessDocumentReceiver, MLR Sender

|Assumptions
a|
.  The BusinessDocumentReceiver has received an electronic business document from the BusinessDocumentSender.
.  The BusinessDocumentReceiver has validated the business document from the BusinessDocumentSender.
.  The result of the validation is not OK due to violation of business rules and syntax.

|The flow
a|
.  The BusinessDocumentSender has prepared and sent an electronic business document to the BusinessDocumentReceiver.
.  The BusinessDocumentReceiver has received the business document.
.  The BusinessDocumentReceiver has validated and rejected the business document.
.  The MLRSender has sent a message level response message back to the MLRReceiver.
.  The MLRReceiver has received and processed the message level response message and performed appropriate action due to the rejection.

|Result
a|
.  The message level response message helped the BusinessDocumentSender to confirm that the business document was received and rejected by the BusinessDocumentReceiver.
The BusinessDocumentSender must take appropriate action to correct and resend the business document.

|XML example file
|See Appendix A for a sample file illustrating Use Case 3.
|====
