
= Allowances and Charges


The order transaction has elements for Allowance/charge on 2 levels.

The element `cac:AllowanceCharge` with sub element `cbc:ChargeIndicator` indicates whether the instance is a charge (true) or an allowance (false).

The header level:: _Applies to the whole order and is included in the calculation of the order total amount (if specified)._
* Several allowances and charges may be supplied
* Specification of TAX for allowances and charges, `cac:TaxCategory` with sub elements, shall be supplied
* The sum of all allowances and charges on the header level shall be specified in `cbc:AllowanceTotalAmount` and `cbc:ChargeTotalAmount` respectively. See <<totals>>

The line level Price element:: _The price itself shall always be the net price, i.e. the base amount reduced with a discount (allowance)._
* Only one occurrence of allowance (discount) is allowed.
* Specification of TAX for allowance shall not be specified
* Allowance related to Price shall not be part of any other calculations.
* Allowance related to Price may specify amount and the base amount.


[allowance-calc]]
== Calculation of allowance/charge amount

Allowance and charge on document level consists of elements carrying information on the allowance/charge base amount
and the allowance/charge percentage. These are, if present in the invoice instance, used for calculating the allowance/charge amount.

If base amount is present, the percentage shall also be present, and if percentage is present, the base amount shall also be present,
and the calculation of the amount shall be:

====
stem:["Amount" =  "Base amount" times ("Percentage" div 100)]
====


.UBL example of Allowances and Charges on the document level where TAX = VAT.
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-01.xml[tags=allowance]
----
<1> ChargeIndicator = true to indicate a charge
<2> ChargeIndicator = false to indicate an allowance
<3> Base amount, to be used with the percentage to calculate the amount
<4> Charge percentage
<5> stem:["Amount" = "Base amount" times ("Percentage" div 100)]


.UBL example showing a discount on price of EUR 10:
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-01.xml[tags=price-discount]
----
